version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  api:
    build: ../apps/api
    command: npm run dev
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    ports:
      - '3000:3000'
    depends_on:
      - db
  web:
    build: ../apps/web
    command: npm run dev -- --host
    ports:
      - '5173:5173'
    depends_on:
      - api
