FROM node:18
WORKDIR /app
COPY ../../package.json ../../package-lock.json* ./
RUN npm install --omit=dev
COPY ../../apps/api ./apps/api
WORKDIR /app/apps/api
RUN npm install && npm run build
CMD ["node", "dist/index.js"]
