FROM node:18
WORKDIR /app
COPY ../../package.json ../../package-lock.json* ./
RUN npm install --omit=dev
COPY ../../apps/web ./apps/web
WORKDIR /app/apps/web
RUN npm install && npm run build
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
